# Generated by Django 2.2.14 on 2021-09-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aladin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
