# Generated by Django 2.2.14 on 2021-09-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aladin', '0003_auto_20210904_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
