# Generated by Django 2.2.14 on 2021-09-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aladin', '0006_auto_20210904_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
