# Generated by Django 2.2.14 on 2021-09-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aladin', '0007_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.FloatField(default=1),
        ),
    ]
