# Generated by Django 2.2.14 on 2021-09-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aladin', '0008_cart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.FloatField(),
        ),
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(to='aladin.cart'),
        ),
    ]
