# Generated by Django 2.2.14 on 2021-09-09 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aladin', '0009_auto_20210909_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='itemss',
        ),
    ]
