# Generated by Django 2.2.14 on 2021-09-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aladin', '0011_auto_20210909_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='itemss',
            field=models.ManyToManyField(to='aladin.item'),
        ),
    ]
