# Generated by Django 2.2.14 on 2021-09-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aladin', '0014_auto_20210910_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='itemss',
            field=models.CharField(max_length=5000),
        ),
    ]
