# Generated by Django 2.2.14 on 2021-09-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aladin', '0015_auto_20210910_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='itemss',
        ),
        migrations.AddField(
            model_name='order',
            name='itemss',
            field=models.ManyToManyField(to='aladin.item'),
        ),
    ]
