# Generated by Django 2.2.14 on 2021-09-10 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aladin', '0016_auto_20210910_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='itemss',
        ),
        migrations.AddField(
            model_name='order',
            name='itemss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aladin.item'),
        ),
    ]
