# Generated by Django 3.2.7 on 2021-09-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aladin', '0018_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='addressa',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
