# Generated by Django 3.2.7 on 2021-09-11 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aladin', '0019_auto_20210911_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='addressa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aladin.address'),
        ),
    ]
