# Generated by Django 3.2.7 on 2021-09-11 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aladin', '0023_alter_order_addressa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='addressa',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='aladin.address'),
        ),
    ]
