# Generated by Django 2.2.14 on 2021-09-14 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aladin', '0025_alter_order_addressa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='namee',
        ),
    ]
